# https://docs.netlify.com/configure-builds/file-based-configuration/
[build]
command = "pnpm run build"
publish = "out/dist"
environment = { NETLIFY_NEXT_PLUGIN_SKIP = "true" }
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
[template.environment]
CL_ORGANIZATION = "Your organization slug"
